### ISSUE TITLE
なべの買い出しする

### ISSUE THREAD

**Issue by hgw** [grandbase/bounen-party-2015#1]
@tadahi 何かあれば追記してください

### メイン
- [x] 出汁 @yst 
- [x] さかな @yst 

### 以下 @tadahi  

- [x] 白菜1つ 
- [x] 人参一袋
- [x] 豆腐 3 丁
- [x] ネギ
- [x] きのこ
- [x] ポン酢
- [x] ガス缶
- [x] 繊細さを活かす塩
- [x] 会を盛り上げてやるぞ、という心意気
- [x] 忘年する意気込み

**Comment by fjm** [comment]
- [ ] 味噌

**Comment by yst** [comment]
###### カワハギの繊細さを活かす塩味を希望するので、味噌はなくとも

**Comment by fjm** [comment]
@yst 

> カワハギの繊細さを活かす塩味を希望するので、味噌はなくとも

:ok_woman:

**Comment by tadahi** [comment]
野菜を切るタイミングを考えているのですが、@yst は何時に到着しますかー？

**Comment by iyamakeiichi** [comment]
@yst 
野菜は切っておきましたー

**Comment by yst** [comment]
釣り過ぎた。もう、30分ちょいで到着します。

**Comment by fjm** [comment]
おいしくいただきました。 close!
![screen 2015-12-24 8 14 31](https://cloud.githubusercontent.com/assets/971124/11986750/6dd77b24-aa16-11e5-9bb4-cc9f624187d5.png)
